### ISSUE TITLE
Presets on uno.config.ts nuxt

### ISSUE THREAD

**Issue by andersonfelix** [jd-solanki/anu#154] opened 2023-04-08 04:54 UTC
When I put `presets: []` on uno config breaks the theme.

"@anu-vue/nuxt": "^0.13.1"

```
export default defineConfig({
  include: [/.*\/anu-vue\.js(.*)?$/, "./**/*.vue", "./**/*.md"],
  presets: [
     presetTypography(),
     presetWebFonts({
      fonts: {
        sans: "DM Sans",
        serif: "DM Serif Display",
        mono: "DM Mono",
        satisfy: "Satisfy",
      },
  ]
})
```

Any suggestion?

**Comment by jd-solanki** [comment] 2023-04-08 16:55
Are you creating seperate `uno.config.ts` file?

**Comment by Sandros94** [comment] 2023-04-08 19:51
I was noticing this too, if you have the presets already configured inside your UnoCSS config it looks like the Anu one gets overwritten.

You can test it in [this reproduction link](https://stackblitz.com/edit/nuxt-anu-issue154?file=unocss.config.ts), but here's what it happens:

### 1. As per reproduction link: I have to specify the imports and the preset parameters to make Anu work correctly.
hypothetical `unocss.config.ts`:
```ts
import { presetAnu, presetIconExtraProperties } from 'anu-vue';
import { presetThemeDefault } from '@anu-vue/preset-theme-default';
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';

export default defineConfig({
  shortcuts: [
    [
      'btn',
      'px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50',
    ],
    [
      'icon-btn',
      'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-teal-600',
    ],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      cdn: 'https://esm.sh/',
      scale: 1.2,
      extraProperties: presetIconExtraProperties,
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
      },
    }),
    // anu-vue preset
    presetAnu(),

    // default theme preset
    presetThemeDefault(),
  ],
  include: [/.*\/anu-vue\.js(.*)?$/, './**/*.vue', './**/*.md'],
  transformers: [transformerDirectives(), transformerVariantGroup()],
});
```
![image](https://user-images.githubusercontent.com/13056429/230739695-47eaa96e-73ca-49c6-8461-dd3fd3c5b878.png)

### 2. removing Anu imports and presets.
from the hypothetical unocss.config.ts lets remove the imports and presets, while leaving the rest as is:
```ts
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';

export default defineConfig({
  shortcuts: [
    [
      'btn',
      'px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50',
    ],
    [
      'icon-btn',
      'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-teal-600',
    ],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      cdn: 'https://esm.sh/',
      scale: 1.2,
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
      },
    }),
  ],
  include: [/.*\/anu-vue\.js(.*)?$/, './**/*.vue', './**/*.md'],
  transformers: [transformerDirectives(), transformerVariantGroup()],
});
```
![image](https://user-images.githubusercontent.com/13056429/230739871-9f6c2d35-33e2-452c-ab12-de381469fc74.png)
Since in dark mode the ASwitch bg blends too much here is another screenshot in light mode:
![image](https://user-images.githubusercontent.com/13056429/230739890-80fa3946-4b96-402b-871a-016bcf032d13.png)

### 3. If I decide to delete the presets entirely
It happened that only once I was able to make it work (idk) in stackblitz without any preset applied, but I'm not able to anymore.
```ts
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';

export default defineConfig({
  shortcuts: [
    [
      'btn',
      'px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50',
    ],
    [
      'icon-btn',
      'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-teal-600',
    ],
  ],
  include: [/.*\/anu-vue\.js(.*)?$/, './**/*.vue', './**/*.md'],
  transformers: [transformerDirectives(), transformerVariantGroup()],
});
```
Since I was retrieving the icons via CDN, and I've deleted the presets entirely, they don't display at all and the ASwitch brakes completely:
![image](https://user-images.githubusercontent.com/13056429/230740032-72922864-0705-4ec7-8f90-5e49e9e3ed6d.png)

Currently I didn't have time to test other components, but I think that it will be a similar story.

**Comment by andersonfelix** [comment] 2023-04-08 20:48
@Sandros94 thank you a lot!

This is necessary:
```js
// anu-vue preset
presetAnu(),

// default theme preset
presetThemeDefault(),
```

**Comment by Sandros94** [comment] 2023-04-08 22:47
> @Sandros94 thank you a lot!
> 
> This is necessary:
> 
> ```js
> // anu-vue preset
> presetAnu(),
> 
> // default theme preset
> presetThemeDefault(),
> ```

Yes they used to be in the doc till @jd-solanki and @cpreston321 removed them to provide a better support for nuxt in #108.
I'm still reading the changes and discussion of that PR, so I'm still not sure if what I understood was intended or I'm off track entirely.

Personally I would have liked a way to configure and use Anu without having to create a `uno.config.ts`, since that wouldn't be bundled with `nuxt.config.ts` using the [nuxt extend feature](https://nuxt.com/docs/examples/advanced/config-extends).

**Comment by jd-solanki** [comment] 2023-04-09 04:49
@andersonfelix if you are creating seperate uno.config.ts file then you need to import and register anu & theme default preset as shown in normal vuejs installation. However, if you are configuring uno via nuxt.config.ts then it will be auto included/merged.

@cpreston321 if someone is creating uno.config.ts file then they have to explicitly import and register anu & theme default preset, right?

**Comment by Sandros94** [comment] 2023-04-09 10:59
I was preparing an example for #155 and while doing so I erroneously blocked unocss from loading some css resets and magically Anu was able to load correctly (but of course other unocss feature stopped working).

You could look [here](https://github.com/Sandros94/test-nuxt3app/commit/0421e9d2b6ba3dd5360e9f1843cab024a3778722), besically up untill this commit I was extending another nuxt project, where the unocss was configured inside `unocss.config.ts` and since the unocss.config didn't extent it could have been the key factor to make Anu visually render.

This is more a stream of thoughts and backlog. I preferred to share it, since In the stackblitz repro you can clearly see that Anu works, its only the styles that brakes.

**Comment by jd-solanki** [comment] 2023-06-07 13:35
Hi @Sandros94 

I tried settings `presets: []` and found that unocss also can't generate utility types without that line. So I guess when we set presets option to empty array UnoCSS stops auto assigning default presets like uno's default & anu.

Can you please confirm?

**Comment by jd-solanki** [comment] 2023-06-10 05:35
Thanks, @Sandros94 for confirmation. I've added this note in the docs in [this](https://github.com/jd-solanki/anu/commit/ace470f683acb8e1bd876c12f61876ecd010c22a#diff-8783c1e123a59b228e62149967dd69769c6b0c000100ca4cfd05e93da2729644) commit.

**Closed** 2023-06-10 05:36 UTC
Labels: nuxt
